version: "2.38.2"
services:
  ath-backend:
    container_name: ath-backend
    build:
      context: .
      target: dev
    restart: always
    ports:
      - 3001:3000
    volumes:
      - ./:/ath-backend
      - /ath-backend/node_modules
